language: java
jdk:
  - oraclejdk8
before_install:
- echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=1024m'" >> ~/.mavenrc
notifications:
  email: false
cache:
  directories:
  - "$HOME/.m2"
addons:
    apt:
        packages:
            - sshpass
    ssh_known_hosts:
      - 51.255.46.42
script: 
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- export SSHPASS=$USER_PWD 
- bash ./compile.sh
after_success:
- bash ./publish.sh
branches:
  only:
    - master
